# Generated by Django 3.1.7 on 2021-03-17 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='times_visited',
        ),
    ]
