# Generated by Django 3.1.7 on 2021-03-17 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_healthhistory_patientfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('position', models.CharField(choices=[('Nurse', 'Nurse'), ('Clinical Officer', 'Clinical Officer'), ('Public Health Officer', 'Public Health Officer'), ('Cleaner', 'Cleaner'), ('Security', 'Security'), ('Driver', 'Driver'), ('Counselor', 'Counselor'), ('Nutritionist', 'Nutritionist')], max_length=100)),
                ('employment_date', models.DateTimeField()),
                ('shift', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescribed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.staff'),
        ),
        migrations.DeleteModel(
            name='Nurse',
        ),
    ]
