# Generated by Django 3.1.7 on 2021-03-17 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20210317_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='price',
            new_name='unit_price',
        ),
    ]
