# Generated by Django 3.1.7 on 2021-03-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_appointment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], max_length=20),
        ),
    ]
