# Generated by Django 3.1.5 on 2021-03-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20210318_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='image',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='image',
        ),
    ]
